SET FOREIGN_KEY_CHECKS=0; -- to disable them
insert into usuarios(usuarioacesso,senhaacesso,nomecompleto,email,contato,usadescontomaximo,descontomaximo,status,deletado)
values('ADMIN',md5('admin'),'ADMINISTRADOR DO SISTEMA','admin@admin.com',99999999999,1,100,1,0);
insert into datahora(datahoracadastro,usuariocadastro,usuarios_idusuarios) values(now(),'SUPORTE',last_insert_id());
-- PERMISSÕES DO SISTEMA
insert into permissoes(idpermissoes,descricaopermissao) values (1,'USUÁRIO PODE TER ACESSO AO SISTEMA PELA TELA DE LOGIN');
insert into permissoes(idpermissoes,descricaopermissao) values (2,'VER DADOS DOS SEUS CAIXAS ANTERIORES');
insert into permissoes(idpermissoes,descricaopermissao) values (3,'VER DADOS DE CAIXAS ANTERIORES DE OUTROS USUÁRIOS');
insert into permissoes(idpermissoes,descricaopermissao) values (4,'DELETAR TRANSAÇÃO DE CAIXAS DE OUTROS USUÁRIOS');
insert into permissoes(idpermissoes,descricaopermissao) values (5,'LANÇAR SUPLEMENTO(ADICIONAR DINHEIRO) NO CAIXA');
insert into permissoes(idpermissoes,descricaopermissao) values (6,'LANÇAR SANGRIA(RETIRAR DINHEIRO) DO CAIXA');
insert into permissoes(idpermissoes,descricaopermissao) values (7,'DELETAR TRANSAÇÃO DO CAIXA ATUAL');
insert into permissoes(idpermissoes,descricaopermissao) values (8,'ABRIR E FECHAR CAIXA');
insert into permissoes(idpermissoes,descricaopermissao) values (9,'EDITAR SALDO INICIAL DO CAIXA');
insert into permissoes(idpermissoes,descricaopermissao) values (10,'DELETAR CAIXA');
insert into permissoes(idpermissoes,descricaopermissao) values (11,'ADICIONAR UMA VENDA PELO PDV');
insert into permissoes(idpermissoes,descricaopermissao) values (12,'FAZER A TROCA/DEVOLUÇÃO DE UMA VENDA');
insert into permissoes(idpermissoes,descricaopermissao) values (13,'DELETAR VENDA');
insert into permissoes(idpermissoes,descricaopermissao) values (14,'ADICIONAR UM NOVO CLIENTE');
insert into permissoes(idpermissoes,descricaopermissao) values (15,'EDITAR UM CLIENTE');
insert into permissoes(idpermissoes,descricaopermissao) values (16,'DELETAR CLIENTE');
insert into permissoes(idpermissoes,descricaopermissao) values (17,'ADICIONAR UM NOVO PRODUTO');
insert into permissoes(idpermissoes,descricaopermissao) values (18,'EDITAR UM PRODUTO');
insert into permissoes(idpermissoes,descricaopermissao) values (19,'DELETAR PRODUTO');
insert into permissoes(idpermissoes,descricaopermissao) values (20,'ADICIONAR ENTRADA NO ESTOQUE');
insert into permissoes(idpermissoes,descricaopermissao) values (21,'ADICIONAR SAÍDA NO ESTOQUE');
insert into permissoes(idpermissoes,descricaopermissao) values (22,'DELETAR TRANSAÇÃO DO ESTOQUE');
insert into permissoes(idpermissoes,descricaopermissao) values (23,'ADICIONAR NOVO DÉBITO CONTA A PAGAR');
insert into permissoes(idpermissoes,descricaopermissao) values (24,'EDITAR DÉBITO CONTA A PAGAR');
insert into permissoes(idpermissoes,descricaopermissao) values (25,'DELETAR DÉBITO CONTA A PAGAR');
insert into permissoes(idpermissoes,descricaopermissao) values (26,'EFETUAR PAGAMENTO DE UM DÉBITO A PAGAR');
insert into permissoes(idpermissoes,descricaopermissao) values (27,'ADICIONAR UM NOVO USUÁRIO');
insert into permissoes(idpermissoes,descricaopermissao) values (28,'EDITAR UM USUÁRIO');
insert into permissoes(idpermissoes,descricaopermissao) values (29,'DELETAR UM USUÁRIO');
insert into permissoes(idpermissoes,descricaopermissao) values (30,'ATIVAR OU DESATIVAR UM USUÁRIO');
insert into permissoes(idpermissoes,descricaopermissao) values (31,'ATIVAR OU DESATIVAR PERMISSÕES DOS USUÁRIOS');
insert into permissoes(idpermissoes,descricaopermissao) values (32,'CLONAR UM USUÁRIO');
insert into permissoes(idpermissoes,descricaopermissao) values (33,'ACESSO A CONFIGURAÇÕES GERIAS DO SISTEMA');
insert into permissoes(idpermissoes,descricaopermissao) values (34,'FAZER BACKUP DO BANCO DE DADOS DO SISTEMA');
insert into permissoes(idpermissoes,descricaopermissao) values (35,'FAZER RESTAURAÇÃO DO BANCO DE DADOS DO SISTEMA');
insert into permissoes(idpermissoes,descricaopermissao) values (36,'ATUALIZAR O SISTEMA');
-- FIM PERMISSÕES

-- ADD PERMISSÃO TOTAL NO USUÁRIO ADMIN
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,1);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,2);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,3);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,4);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,5);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,6);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,7);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,8);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,9);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,10);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,11);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,12);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,13);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,14);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,15);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,16);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,17);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,18);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,19);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,20);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,21);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,22);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,23);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,24);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,25);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,26);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,27);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,28);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,29);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,30);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,31);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,32);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,33);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,34);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,35);
insert into usuario_tem_permissao(status,usuarios_idusuarios,permissoes_idpermissoes) values (1,1,36);
-- FIM ADD PERMISSÃO ADMIN
insert into configuracoesgerais(idconfiguracoesgerais,trocomaximo,valortrocomaximo,imprimircpfcnpjnocupom,imprimircupomfinalizarvenda,imprimircupomfiscalnfcefinalizarvenda,imprimirnomevendedorfinalizarvenda,vendacartaopermitirdesconto,avisarclienteaniversariante,avisarprodutoestoquebaixo) values (1,0,0,0,1,0,0,0,0,1);
insert into apifocusnfe(idapifocusnfe,usarapi,tokenhomologacao,tokenproducao,ambiente,indicadoriedestinatario,clientespessoas_idclientespessoas) values (1,0,'','','','',null);
insert into apigerencianet(idapigerencianet,usarapi,clientidhomologacao,clientsecrethomologacao,clientidproducao,clientsecretproducao,ambiente) values (1,0,'','','','','');
insert into emailsistema(idemailsistema,emailprincipal,emailcopia1,emailcopia2) values (1,'','','');